### ISSUE TITLE
Is purr capable of extracting fields within objects

### ISSUE THREAD

**Issue by stieg** [boosterfuels/purr#56]
Hello devs,

   Question for you all here since I can't quite figure this out.  Say I have a collection called airports that has a record that looks something like this:

```js
{
  name: "foo",
  location: {
    latitude: 1.23,
    longitude: 4.56,
  }
}
```

My goal is to extract the values of latitude and longitude into their own columns in Postgres.  I have setup my config file as follows:

```yml
demodb:
  airports:
    :columns:
    - :source: _id
      :type: TEXT
      id: null
    - :source: 'location.latitude'
      :type: DOUBLE PRECISION
      location__latitude: null
    - :source: 'location.longitude'
      :type: DOUBLE PRECISION
      location__longitude: null
    - :source: name
      :type: TEXT
      name: null
    :meta:
      :extra_props: JSONB
      :table: airports
``` 

When I run purr it creates the columns on my postgres db but the values do not come over.  Is there something I am doing wrong here?  I have tried with and without quotes and I have also tried escaping the quotes in the config file.  Thanks in advance.
